version: '3.7'

services:
  mysql:
    image: mysql
    container_name: mysql-database
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ordersfood
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - common-network

  backend:
    depends_on: 
      - mysql
    # image: backend
    container_name: web-springboot
    build: 
      context: OrdersFood
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ordersfood?createDatabaseIfNotExist=true&failOverReadOnly=false&maxReconnects=10
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    networks:
      - common-network
      
  angular-service:
    depends_on: 
      - backend
    container_name: client-angular
    build:
      context: OrdersFood-FE
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    # restart: always
    networks:
      - common-network

#Docker Networks
networks:
    common-network:
        driver: bridge

#Volumes
volumes:
    db_data:
        driver: local