version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: workapp
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - common-network

  backend:
    depends_on: 
      - mysql
    # image: backend
    #container_name: web-springboot
    build: 
      context: work-app
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/workapp?createDatabaseIfNotExist=true&failOverReadOnly=false&maxReconnects=10
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    networks:
      - common-network
    volumes:
      - db_data:/var/lib/mysql

#Docker Networks
networks:
    common-network:
        driver: bridge

#Volumes
volumes:
    db_data:
        driver: local